import { type NextPage } from "next";
import Head from "next/head";

import SideBar from "./components/sidebar";
import { useUploadedData, useUserSteps } from "./store/store";
import FileInput from "./components/readFiles";
import CSVUpload from "./components/read3";
import JustUploaded from "./components/content/justUploaded";
import { api } from "~/utils/api";
import { PROSPECT } from "~/utils/types";

const Home: NextPage = () => {
 // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const upload=api.example.upload.useMutation()
 const {currentTab,setCurrentTab}=useUserSteps()
  const {data,isDataUploaded,setDataIsUploaded,setUploadedData}=useUploadedData()

  const onFileLoaded =(e:object[])=>{
        console.log(e)
  }

  const uploadData=()=>{
   const newdata=data.map((item,index)=>{
    if(index!=51){
      return item
    }
   })
      const result=upload.mutate(newdata as PROSPECT[])

    }  

  return (
    <>
      <Head>
        <title>CAll assistant app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className=" min-h-screen flex bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="h-full min-h-screen w-64  ">
          <SideBar/>
        </div>
        <div className=" min-h-screen w-2 h-full bg-white"></div>
        <div className="w-full flex-grow flex justify-center pt-20 max-h-screen">
              {currentTab=='reader'&&<CSVUpload />}
              {currentTab=='uploaded'&&<div className=" flex flex-col ">
                <button  className=" px-3 py-1 w-fit mx-auto bg-white rounded-xl">Save data to the database</button>
                <JustUploaded />

                </div>
                }
              
        </div>
    </main> 
    </>
  );
};

export default Home;

